myset = {"apple", "banana", "cherry"}
print(myset)
print(type(myset))
thisset=set(('apple','banana','chiku'))
print(thisset)
print(type(thisset))
thisset.add('mango')
print(thisset)
fruits=thisset.copy()
print(fruits)
thisset.pop()
print(thisset)
fruits.remove('chiku')
print(fruits)
fruits.clear()
print(fruits)